### ISSUE TITLE
messages.get can return empty messages due to move msgId renumbering, and date and folder is still set

### ISSUE THREAD

**Issue by opto** [thunderbird/webext-docs#59]
After  a message is moved, I can still get a message at the old id, it has a date (1970) and a folder set.

Put that into the documentation? Remove date and folder? Indicate somehow that it is not a valid message?

This somehow reminds me of the old Gloda (bug) where a Glodamsg can have an empty folder msg (i.e. being invalid).
Maybe we can somehow invalidate the id or indicate it is not valid??.

**Comment by jobisoft** [comment]
That is a bug, should be sorted out when we enforce the id to remain the same on move. When you file a bug for the keep-id-on-move, please mention this issue as well.

**Comment by jobisoft** [comment]
Handled in https://bugzilla.mozilla.org/show_bug.cgi?id=1855486
